using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


/// AUTOGENERATED FROM RUBYSOURCE
namespace Podio.API.Model
{
	[DataContract]
	public partial class Live
	{


		[DataMember(Name = "status", IsRequired=false)]
		public string Status { get; set; }


		[DataMember(Name = "presence", IsRequired=false)]
		public Dictionary<string,object> Presence { get; set; }


		[DataMember(Name = "provider", IsRequired=false)]
		public string Provider { get; set; }


		[DataMember(Name = "push", IsRequired=false)]
		public Dictionary<string,object> Push { get; set; }


		[DataMember(Name = "live_id", IsRequired=false)]
		public int? LiveId { get; set; }


		[DataMember(Name = "settings", IsRequired=false)]
		public Dictionary<string,object> Settings { get; set; }


		[DataMember(Name = "ref", IsRequired=false)]
		public Dictionary<string,object> Ref { get; set; }


	}
}

